### ISSUE TITLE
Adding a JSON or TXT wallpapers index API

### ISSUE THREAD

**Issue by Sovenok-Hacker** [my-wallpapers/my-wallpapers.github.io#5]
What about making a GitHub Action for writing an index file for downloading in code?
I am working on a wallpaper changer in Rust and I think it will be great to create an index file.

**Comment by PatrickStar8753** [comment]
Do you mean this? https://patrickstar8753.github.io/randomwallpaper/wallpapers.json

**Comment by Sovenok-Hacker** [comment]
Oh, thanks Max
